# Generated by Django 2.2.4 on 2020-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nms_server', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('btsstatus', models.BooleanField(default=False)),
                ('hvacstatus', models.BooleanField(default=False)),
                ('txnstatus', models.BooleanField(default=False)),
                ('hvac_pin', models.IntegerField(null=True, verbose_name='HVAC-PIN')),
                ('bts_pin', models.IntegerField(null=True, verbose_name='BTS-PIN')),
            ],
        ),
    ]
