# Generated by Django 2.2.4 on 2020-01-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0002_auto_20200122_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='bts_pin',
            field=models.IntegerField(default=0, verbose_name='BTS-PIN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='hvac_pin',
            field=models.IntegerField(default=0, verbose_name='HVAC-PIN'),
            preserve_default=False,
        ),
    ]
