# Generated by Django 2.2.4 on 2020-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0002_auto_20200207_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='IP',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
