# Generated by Django 2.2.4 on 2020-01-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0003_auto_20200123_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='bts_pin',
            field=models.IntegerField(null=True, verbose_name='BTS-PIN'),
        ),
        migrations.AlterField(
            model_name='module',
            name='hvac_pin',
            field=models.IntegerField(null=True, verbose_name='HVAC-PIN'),
        ),
    ]
