# Generated by Django 2.2.4 on 2020-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0003_module_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='txn_offline_counter',
            field=models.IntegerField(null=True, verbose_name='TXN-OFF-COUNTER'),
        ),
        migrations.AddField(
            model_name='module',
            name='txn_online_counter',
            field=models.IntegerField(null=True, verbose_name='TXN-ON-COUNTER'),
        ),
    ]
