# Generated by Django 2.2.4 on 2020-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0004_auto_20200218_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='txn_offline_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='TXN-OFF-COUNTER'),
        ),
        migrations.AlterField(
            model_name='module',
            name='txn_online_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='TXN-ON-COUNTER'),
        ),
    ]
