# Generated by Django 2.2.4 on 2020-03-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0005_auto_20200218_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='gen_pin',
            field=models.IntegerField(null=True, verbose_name='BTS-PIN'),
        ),
        migrations.AddField(
            model_name='module',
            name='genstatus',
            field=models.BooleanField(default=False),
        ),
    ]
