# Generated by Django 2.2.4 on 2020-03-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0006_auto_20200314_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='gen_pin',
            field=models.IntegerField(null=True, verbose_name='GEN-PIN'),
        ),
    ]
