# Generated by Django 2.2.4 on 2020-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0007_auto_20200314_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='mainsstatus',
            field=models.BooleanField(default=False),
        ),
    ]
