# Generated by Django 2.2.4 on 2020-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pimoduleapp', '0008_module_mainsstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='mains_pin',
            field=models.IntegerField(null=True, verbose_name='MAIN-PIN'),
        ),
    ]
